# The Site Configuration # 網站設定檔，設定整個 Jekyll 網站的行為

# Import the theme # 匯入主題，這裡使用 chirpy 主題
theme: jekyll-theme-chirpy # 網站主題名稱

# The language of the webpage › http://www.lingoes.net/en/translator/langcode.htm # 網站語言設定
# If it has the same name as one of the files in folder `_data/locales`, the layout language will also be changed, # 若與 _data/locales 下的檔案同名，則會自動切換語系
# otherwise, the layout language will use the default value of 'en'. # 否則預設為英文
lang: en # 網站語言（如 zh-TW、en）

# Change to your timezone › https://kevinnovak.github.io/Time-Zone-Picker # 設定網站時區
timezone: Asia/Taipei # 請填入你的時區（如 Asia/Taipei）

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md # SEO 設定區塊
# ↓ --------------------------


title: jcleealg # 網站主標題，會顯示在瀏覽器標籤與首頁

tagline: From coffee to code, from theorems to tools. # 網站副標題，顯示於主標題下方

description: Fueled by coffee, this site documents a journey of transforming abstract mathematical theorems into practical, problem-solving tools. Come see what's brewing. # 網站描述，會用於 SEO meta 與 RSS feed

# Fill in the protocol & hostname for your site. # 設定網站網址
# E.g. 'https://username.github.io', note that it does not end with a '/'. # 範例格式
url: "https://jcleealg.github.io" # 你的網站網址（不以 / 結尾）


github: # GitHub 設定區塊
  username: jcleealg # 你的 GitHub 帳號


# twitter: # Twitter 設定區塊
#   username: # 你的 Twitter 帳號


social: # 社群資訊設定
  name: jcleealg # 你的全名，會顯示於頁腳與文章作者
  email: # 你的電子郵件
  links: # 社群連結清單
    # - https://twitter.com/username # 你的 Twitter 連結
    - https://github.com/jcleealg # 你的 GitHub 連結
    # - https://www.facebook.com/username # 其他社群（可取消註解）
    # - https://www.linkedin.com/in/username


# Site Verification Settings # 站長驗證碼設定（用於搜尋引擎驗證）
webmaster_verifications:
  google: # Google 驗證碼
  bing: # Bing 驗證碼
  alexa: # Alexa 驗證碼
  yandex: # Yandex 驗證碼
  baidu: # 百度驗證碼
  facebook: # Facebook 驗證碼


# ↑ --------------------------
# The end of `jekyll-seo-tag` settings # SEO 設定結束


# Web Analytics Settings # 網站流量分析設定
analytics:
  google:
    id: # Google Analytics 追蹤碼
  goatcounter:
    id: # GoatCounter 追蹤碼
  umami:
    id: # Umami 追蹤碼
    domain: # Umami 網域
  matomo:
    id: # Matomo 追蹤碼
    domain: # Matomo 網域
  cloudflare:
    id: # Cloudflare Web Analytics token
  fathom:
    id: # Fathom Site ID


# Page views settings # 網頁瀏覽次數設定
pageviews:
  provider: # 現在僅支援 goatcounter


# Prefer color scheme setting. # 預設顏色主題
# 留空則跟隨系統，側邊欄左下可切換
# 可選 light（亮色）或 dark（暗色）
theme_mode: # [light | dark]


# The CDN endpoint for media resources. # 媒體資源 CDN 設定
# 設定後，所有以 / 開頭的媒體路徑都會加上 CDN 網址
cdn:


# the avatar on sidebar, support local or CORS resources # 側邊欄頭像設定
avatar: /assets/img/SteppeCat_01.jpg


# The URL of the site-wide social preview image used in SEO `og:image` meta tag. # SEO 預覽圖設定
# 可被單篇文章的 page.image 覆蓋
social_preview_image: # 網站預設預覽圖網址


# boolean type, the global switch for TOC in posts. # 全域 TOC（目錄）開關
toc: true # 是否在文章顯示目錄


comments: # 留言系統設定
  provider: # 留空為關閉，可選 disqus、utterances、giscus
  disqus:
    shortname: # Disqus 短網址名稱
  utterances:
    repo: # utterances 對應的 GitHub repo
    issue_term: # 對應的 issue 條件
  giscus:
    repo: # giscus 對應的 GitHub repo
    repo_id: # giscus repo id
    category: # giscus 分類
    category_id: # giscus 分類 id
    mapping: # 對應方式，預設 pathname
    strict: # 是否嚴格對應
    input_position: # 留言框位置
    lang: # 留言語言
    reactions_enabled: # 是否啟用表情回應


# Self-hosted static assets, optional # 是否自架靜態資源
assets:
  self_host:
    enabled: # 啟用自架靜態資源（true/false）
    env: # 指定環境（development/production）


pwa: # PWA（漸進式網頁應用）設定
  enabled: true # 是否啟用 PWA 功能（可安裝）
  cache:
    enabled: true # 是否啟用離線快取
    deny_paths: # 排除不快取的路徑
      # - "/example"  # 這些路徑不會被 PWA 快取


paginate: 10 # 每頁顯示的文章數量


# The base URL of your site # 網站子目錄（通常 GitHub Pages 個人頁面留空，專案頁面填 repo 名稱）
baseurl: ""


# ------------ The following options are not recommended to be modified ------------------ # 以下設定通常不需更動


kramdown: # Markdown 解析器設定
  footnote_backlink: "&#8617;&#xfe0e;" # 註腳返回符號
  syntax_highlighter: rouge # 語法高亮工具
  syntax_highlighter_opts: # Rouge 選項
    css_class: highlight # 高亮 class 名稱
    # default_lang: console # 預設語言
    span:
      line_numbers: false # 行內程式碼不顯示行號
    block:
      line_numbers: true # 區塊程式碼顯示行號
      start_line: 1 # 行號起始值


collections: # Jekyll collections 設定
  tabs:
    output: true # 產生對應的靜態頁面
    sort_by: order # 依 order 排序


defaults: # 預設 Front Matter 設定
  - scope:
      path: "" # 作用於所有 posts
      type: posts
    values:
      layout: post # 預設版型為 post
      comments: true # 預設開啟留言
      toc: true # 預設顯示目錄
      permalink: /posts/:title/ # 文章網址格式
  - scope:
      path: _drafts # 草稿資料夾
    values:
      comments: false # 草稿預設不開啟留言
  - scope:
      path: ""
      type: tabs # 作用於 tabs collection
    values:
      layout: page # 預設版型為 page
      permalink: /:title/ # 頁面網址格式


sass: # Sass 預處理器設定
  style: compressed # 輸出壓縮格式


compress_html: # HTML 壓縮設定
  clippings: all # 移除所有片段
  comments: all # 移除所有註解
  endings: all # 移除所有結尾空白
  profile: false # 不啟用 profile
  blanklines: false # 不保留空白行
  ignore:
    envs: [development] # 開發環境不壓縮


exclude: # 不納入編譯的檔案或資料夾
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"


jekyll-archives: # Jekyll 分類與標籤歸檔設定
  enabled: [categories, tags] # 啟用分類與標籤歸檔
  layouts:
    category: category # 分類頁版型
    tag: tag # 標籤頁版型
  permalinks:
    tag: /tags/:name/ # 標籤頁網址格式
    category: /categories/:name/ # 分類頁網址格式
